version: '2.0'
services:
    db:
        container_name: "${COMPOSE_PROJECT_NAME}_db"
        image: mariadb:latest
        volumes:
            - ../:/opt
        working_dir: /opt
        env_file: .env
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: "${COMPOSE_PROJECT_NAME}_phpmyadmin"
        links:
            - db
        env_file: .env
    phpfpm:
        container_name: "${COMPOSE_PROJECT_NAME}_${COMPOSE_PHP_MODULE}"
        image: cubesdoo/php-fpm:latest
        volumes:
            - ../:/opt
            - ./phpfpm.conf:/usr/local/etc/php-fpm.d/default.conf
            - ./php.ini:/usr/local/etc/php/conf.d/php.ini
        working_dir: /opt
        links:
            - db
        env_file: .env
    nginx:
        container_name: "${COMPOSE_PROJECT_NAME}_${COMPOSE_WEB_SERVER}"
        image: nginx:latest
        ports:
            - "$EXTERNAL_PORT:80"
        volumes:
            - ../:/opt
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        working_dir: /opt
        links:
            - phpfpm
            - phpmyadmin
        env_file: .env
        